import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Tesseract browser runtime copied from node_modules by
    // scripts/copy-ocr-assets.mjs — vendor minified output, not our source.
    "public/tesseract/**",
    // Built WebExtension bundles (`npm run ext`). Generated output, and it
    // contains the engine inlined — linting it reports the bundler's
    // transformations as if they were ours.
    "extension/dist/**",
    // The Safari wrapper (`npm run ext:safari`) — an Xcode project generated by
    // Apple's converter, carrying a copy of the built bundle above.
    "extension/safari/**",
  ]),
  // ── Privacy invariant: no low-level network access in the detector ─────────
  //
  // The app's core promise is that submitting a suspicious link does not visit
  // it. Fetching a scam URL tells the scammer their link is live and under
  // investigation, which can cost a victim their one chance at a takedown.
  //
  // __tests__/privacyInvariant.test.ts enforces this behaviourally, but it can
  // only intercept global fetch: module mocking cannot reach a dynamic import
  // inside already-loaded production code, so a leak through node:dns or
  // node:net would pass every test in that file. The route contract in
  // app/api/check/route.ts explicitly names "an outbound HTTP request, DNS
  // lookup, or socket connection" — these rules close the two the test cannot,
  // for first-party code. They are static analysis, not a sandbox: a name
  // assembled at runtime still slips through, as does a dependency doing it
  // for us. The point is to make a leak cost a deliberate, visible act.
  //
  // Scoped to the code that handles submitted content. Scripts and workers are
  // deliberately excluded: they do legitimate network work and never analyse a
  // user's submission. Non-network builtins (crypto, path, fs) stay allowed —
  // this bans reaching the network, not using Node.
  //
  // If a future change genuinely needs one of these, that is a deliberate
  // decision about the privacy contract and should be argued in review, not
  // silenced with an inline disable.
  {
    // packages/** is listed because the engine moved there. Leaving it out was
    // a real regression during the extraction: lint kept passing while the
    // rules silently stopped covering the one module they exist for. A scope
    // that no longer matches the code is indistinguishable from a scope that
    // finds nothing — which is why __tests__/engineNetworkImports.test.ts
    // probes the engine's own path rather than trusting this list.
    files: [
      "lib/**/*.{ts,tsx}",
      "app/**/*.{ts,tsx}",
      "components/**/*.{ts,tsx}",
      "packages/**/*.{ts,tsx}",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            "dns", "node:dns", "dns/promises", "node:dns/promises",
            "net", "node:net",
            "tls", "node:tls",
            "http", "node:http",
            "https", "node:https",
            "http2", "node:http2",
            "dgram", "node:dgram",
          ].map((name) => ({
            name,
            message:
              "Network access from the detector would break the never-visit-a-submitted-URL invariant. " +
              "Outbound calls go through the injected transport (see packages/engine/src/urlExpander.ts) or an explicit " +
              "fetch to a fixed endpoint we chose. See __tests__/privacyInvariant.test.ts.",
          })),
        },
      ],
      // no-restricted-imports only sees static import statements. A dynamic
      // `await import("node:dns")` or a `require("node:net")` slips straight
      // past it — and that is exactly the shape the behavioural test cannot see
      // either, because module mocking does not reach a dynamic import inside
      // already-loaded code. Without this selector the channel is enforced by
      // neither half.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            'ImportExpression > Literal[value=/^(node:)?(dns|net|tls|http|https|http2|dgram)(\\/.*)?$/]',
          message:
            "Dynamic import of a Node network module would break the never-visit-a-submitted-URL invariant. " +
            "See __tests__/privacyInvariant.test.ts and eslint.config.mjs.",
        },
        {
          selector:
            'CallExpression[callee.name="require"] > Literal[value=/^(node:)?(dns|net|tls|http|https|http2|dgram)(\\/.*)?$/]',
          message:
            "require() of a Node network module would break the never-visit-a-submitted-URL invariant. " +
            "See __tests__/privacyInvariant.test.ts and eslint.config.mjs.",
        },
      ],
    },
  },
  // Treat a leading underscore as "deliberately unused". Needed for the
  // omit-a-key destructure idiom (`const { dropMe: _, ...rest } = obj`) and
  // for signature-mandated parameters that go unread.
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
]);

export default eslintConfig;
